version: '3.2'
services:
  prometheus:
    image: docker-registry-default.bvnet.bv/openshift/prometheus:v3.9.102-1
    container_name: prometheus
    ports:
      - 9060:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "app:${EXTERNAL_IP}"
    env_file: docker-compose.env
  grafana:
    image: mirror.gcr.io/grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards/:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
    extra_hosts:
      - "app:${EXTERNAL_IP}"